server:
    port: 8081

spring:
    jpa:
        hibernate:
            ddl-auto: validate
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/vehicles
        username: ${DB_USER:root}
        password: ${DB_PASSWORD:vehicles}
        driver-class-name: com.mysql.cj.jdbc.Driver
    application:
        name: vehicles-backend
    data:
        jackson:
            property-naming-strategy: SNAKE_CASE
    kafka:
        bootstrap-servers: localhost:9094
        consumer:
            group-id: vehicles-app
management:
    endpoint:
        health:
            show-details: always
            group.liveness.include: livenessProbe,db
    health:
        probes.enabled: true
        binders.enabled: false
        diskspace.enabled: false
    endpoints:
        web:
            exposure:
                include: health,prometheus
            base-path: '/'
            path-mapping:
                prometheus: 'metrics'

springdoc:
    api-docs:
        path: /api-docs
        resolve-schema-properties: true

    override-with-generic-response: false
    paths-to-exclude: /**/api-docs,/swagger-resources/**
    swagger-ui:
        path: /